### ISSUE TITLE
Better error message if feature folder does not contain info.yaml

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/builder#22]
**What would you like to be added**:
An error message that tells the developer that the `info.yaml` is missing for a given feature. 

**Why is this needed**:
<img width="445" alt="Screenshot 2023-07-12 at 16 45 30" src="https://github.com/gardenlinux/builder/assets/2008076/b1bf23c1-1870-439d-91f7-dad11aba4f1d">

@fwilhe thanks for reporting

**Comment by fwilhe** [comment]
Note to self: Got bitten by this again.

Situation: In https://github.com/gardenlinux/ostree-image-builder I have a subset of the gardenlinux repo and wanted to sync my copy with upstream. I don't include all features, and one of the features I removed was the 'sap' feature as it is not needed. But this is declared in the `info.yaml` of the server feature. This led to the "dictionary changed size during iteration" message.
