### ISSUE TITLE
Usability: Warn about too little memory in podman/docker virtual machine

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/builder#88]
**What would you like to be added**:

Warn the user about probably too small memory capacity.

**Why is this needed**:

For everyone using the builder not on a native linux machine, one needs a virtual machine (or a remote host) to run linux containers via podman or docker.
Both podman and docker have solutions for this that take care of setting up a vm on the user's behalf.
The issue is that the default amount of memory they allocate is probably too small to build Garden Linux.
To the user, this will make the build fail in non-obvious ways.

Questions:
- What is the recommended lower bound? 4GiB? 8GiB?
- Is a simple print enough or should it be a prompt where the user explicitly needs to accept (via keypress or environment variable) that they want to continue despite little memory?

**Comment by fwilhe** [comment]
ping @Akendo (I think you mentioned this as an issue)
@nkraetzschmar

**Comment by Vincinator** [comment]
we could read available memory from `/proc/meminfo` and convert it for a check that we place for example here:
https://github.com/gardenlinux/builder/blob/11da87307abc64c4d548729cb5a00e8e277e7d42/builder/image.d/make_reproducible_ext4#L75

**Comment by Vincinator** [comment]
With regards to the threshold value for the warning message: 
@nkraetzschmar mentioned, ideally 4GB should suffice. Maybe a cleanup step is broken somewhere.

**Comment by Vincinator** [comment]
@fwilhe is this fixed by #89?

**Comment by fwilhe** [comment]
> @fwilhe is this fixed by #89?

From a UX perspective I don't think so. I think it's good we set explicit limits and reduce memory usage where possible (thanks for that @nkraetzschmar), but if the build runs out of memory, the failure will still be non-obvious.

I don't know how easy we could implement a lower-bounds check for memory in the builder (might not be trivial or possible due to linux namespaces), but I'd prefer to keep this issue open until further investigation to decide if we can/want to improve this or not.
